var cli=require("./Client.js"),data=require("./Data.js"),FileHelper=require("./Helper.js");
function LogicServer(){this.clients={};this.cid_seed=0;this.cli_web_map={};this.cli_topic=this.cli_ue4d=this.cli_ue4=this.cli_ros=null;data.load(this);this.genCid=function(){return this.cid_seed+=1};this.isAuth=function(b){return void 0!=b.auth};this.cid2socket=function(b){return null==info?null:this.clients[b].socket};this.socket2cid=function(b){b=b.client;return null==b?null:b.cid};this.addClient=function(b,a){if(a.auth){var c=a.client;return c}a.auth=!0;var d=this.genCid();c=cli.create(b,d,a);
c.type=b;c.logic=this;console.log("$$$$$$$$$ cid:"+d);this.clients[d]=c;a.client=c;a.cid=d;switch(b){case 0:this.cli_web_map[d]=c;break;case 1:this.cli_ros=c;break;case 2:this.cli_ue4=c;break;case 3:this.cli_ue4d=c;break;case 4:this.cli_topic=c}return c};this.removeSocket=function(b){var a=b.client;null!=a&&(a.isWeb()&&delete this.cli_web_map[b.cid],a.isRos()&&(this.cli_ros=null),a.isUE4()&&(this.cli_ue4=null),a.isUE4d()&&(this.cli_ue4d=null),a.isTopic()&&(this.cli_topic=null),delete this.clients[a.cid])};
this.removeClient=function(b){b=this.clients[b];null!=b&&this.removeSocket(b.socket)};this.send2Client=function(b,a){b=this.clients[b];null!=b&&b.send(a)};this.send2Socket=function(b,a){b=b.client;null!=b&&b.send(a)};this.broadcast=function(b,a){for(var c in this.clients){var d=this.clients[c];d!=a&&d.send(b)}};this.send2web=function(b){for(var a in this.cli_web_map)this.cli_web_map[a].send(b)};this.send2ros=function(b){null!=this.cli_ros&&this.cli_ros.send(b)};this.send2ue4=function(b){null!=this.cli_ue4&&
this.cli_ue4.send(b)};this.send2ue4d=function(b){null!=this.cli_ue4d&&this.cli_ue4d.send(b)};this.send2topic=function(b){null!=this.cli_topic&&this.cli_topic.send(b)};this.procAuth=function(b,a){var c=this.addClient(a.type,b);console.log("============>auth %d | %s | %s",c.cid,c.remoteAddress,JSON.stringify(a));a.cid=c.cid;a.msg="welcome!";c.send(a);switch(a.type){case 0:c.send(this.SceneInfo);c.send(this.WeatherInfo);c.send(this.TrafficInfo);c.send(this.CarConfig);c.send(this.CarConfigList);c.send(this.RosInfo);
c.send(this.CaseList);break;case 1:if(null!=this.cli_ue4){b={method:"set_ue4_ip",ip:this.cli_ue4.remoteAddress};this.send2ros(b);break}case 2:this.send2ue4(this.SceneInfo),b={method:"set_ue4_ip",ip:b.remoteAddress},this.send2ros(b)}};this.procMessage=function(b,a){b=b.client;console.log("receivedPack: %s:!!!%s!!!",b.remoteAddress,JSON.stringify(a));switch(a.method){case "chat":this.broadcast(a);break;case "scene_info":this.SceneInfo=a;FileHelper.saveJSONToFile("config/SceneInfo",a);this.send2ue4(a);
break;case "weather_info":this.WeatherInfo=a;FileHelper.saveJSONToFile("config/WeatherInfo",a);this.send2ue4(a);break;case "traffic_info":this.TrafficInfo=a;FileHelper.saveJSONToFile("config/TrafficInfo",a);this.send2ue4(a);break;case "ros_info":this.RosInfo=a;b.isWeb()?(null!=this.cli_ue4&&(a.ip=this.cli_ue4.remoteAddress),this.send2ros(a)):b.isRos()&&this.send2web(a);break;case "car_config":this.CarConfig=a;FileHelper.saveJSONToFile("config/CarConfig",a);this.send2ue4(a);break;case "car_config_list":this.CarConfigList=
a;FileHelper.saveJSONToFile("config/CarConfigList",a);break;case "loading":this.send2web(a);this.send2ue4(this.WeatherInfo);this.send2ue4(this.TrafficInfo);this.send2ue4(this.CarConfig);this.send2ue4(this.CaseList);break;case "car_state":this.CarState=a;b.isWeb()?this.send2ue4(this.CarState):b.isUE4()&&this.send2web(this.CarState);break;case "case_list":this.CaseList=a;FileHelper.saveJSONToFile("config/CaseList",a);b.isWeb()?this.send2ue4(a):b.isUE4()&&this.send2web(a);break;case "case_info":b.isWeb()?
this.send2ue4(a):b.isUE4()&&this.send2web(a);break;case "sumo_info":b.isWeb()?this.send2ue4(a):b.isUE4()&&this.send2web(a);break;case "drive_info":b.isRos()?this.send2web(a):b.isWeb()&&this.send2ros(a);break;case "topic_info":b.isTopic()&&this.send2web(a);break;case "get":a.value=FileHelper.loadStringFromFile(a.key);b.send(a);break;case "set":FileHelper.saveStringToFile("db/"+a.key,a.value);break;case "ping":b.send(a);break;default:console.log("|||||||||||||||unknow pack:%s",a.method)}}}
exports.LogicServer=LogicServer;
