var cli=require("./Client.js"),data=require("./Data.js"),FileHelper=require("./Helper.js");
function LogicServer(){this.clients={};this.cids={};this.cid_seed=0;this.cli_web_map={};this.cli_topic=this.cli_ue4d=this.cli_ue4=this.cli_ros=null;data.load(this);this.genCid=function(){return this.cid_seed+=1};this.isAuth=function(a){return void 0!=a.auth};this.cid2socket=function(a){return null==info?null:this.clients[a].socket};this.socket2cid=function(a){a=a.client;return null==a?null:a.cid};this.addClient=function(a,b){if(b.auth){var c=b.client;return c}b.auth=!0;var d=this.genCid();c=cli.create(a,
d,b);c.type=a;console.log("$$$$$$$$$ cid:"+d);this.clients[d]=c;b.client=c;b.cid=d;this.cids[d]=c;switch(a){case 0:this.cli_web_map[d]=c;break;case 1:this.cli_ros=c;break;case 2:this.cli_ue4=c;break;case 3:this.cli_ue4d=c;break;case 4:this.cli_topic=c}return c};this.removeSocket=function(a){var b=a.client;null!=b&&(b.type=0,this.cli_ros==a&&(this.cli_ros=null),this.cli_ue4==a&&(this.cli_ue4=null),this.cli_ue4d==a&&(this.cli_ue4d=null),this.cli_topic==a&&(this.cli_topic=null),a=b.cid,delete this.clients[a],
delete this.cids[a])};this.removeClient=function(a){null!=this.clients[a]&&delete this.clients[a]};this.send2Client=function(a,b){a=this.clients[a];null!=a&&a.send(b)};this.send2Socket=function(a,b){a=a.client;null!=a&&a.send(b)};this.broadcast=function(a,b){for(var c in this.cids){var d=this.cids[c];d!=b&&d.send(a)}};this.send2web=function(a){for(var b in this.cli_web_map)this.cli_web_map[b].send(a)};this.send2ros=function(a){null!=this.cli_ros&&this.cli_ros.send(a)};this.send2ue4=function(a){null!=
this.cli_ue4&&this.cli_ue4.send(a)};this.send2ue4d=function(a){null!=this.cli_ue4d&&this.cli_ue4d.send(a)};this.send2topic=function(a){null!=this.cli_topic&&this.cli_topic.send(a)};this.procAuth=function(a,b){var c=this.addClient(b.type,a);console.log("============>auth %d | %s | %s",c.cid,c.remoteAddress,JSON.stringify(b));b.cid=c.cid;b.msg="welcome!";c.send(b);switch(b.type){case 0:c.send(this.SceneInfo);c.send(this.WeatherInfo);c.send(this.TrafficInfo);c.send(this.CarConfig);c.send(this.CarConfigList);
c.send(this.RosInfo);c.send(this.CaseList);break;case 1:if(null!=this.cli_ue4){a={method:"set_ue4_ip",ip:this.cli_ue4.remoteAddress};this.send2ros(a);break}case 2:this.send2ue4(this.SceneInfo),a={method:"set_ue4_ip",ip:a.remoteAddress},this.send2ros(a)}};this.procMessage=function(a,b){a=a.client;console.log("receivedPack: %s:!!!%s!!!",a.remoteAddress,JSON.stringify(b));switch(b.method){case "chat":this.broadcast(b);break;case "scene_info":this.SceneInfo=b;FileHelper.saveJSONToFile("config/SceneInfo",
b);this.send2ue4(b);break;case "weather_info":this.WeatherInfo=b;FileHelper.saveJSONToFile("config/WeatherInfo",b);this.send2ue4(b);break;case "traffic_info":this.TrafficInfo=b;FileHelper.saveJSONToFile("config/TrafficInfo",b);this.send2ue4(b);break;case "ros_info":this.RosInfo=b;a.isWeb()?(null!=this.cli_ue4&&(b.ip=this.cli_ue4.remoteAddress),this.send2ros(b)):a.isRos()&&this.send2web(b);break;case "car_config":this.CarConfig=b;FileHelper.saveJSONToFile("config/CarConfig",b);this.send2ue4(b);break;
case "car_config_list":this.CarConfigList=b;FileHelper.saveJSONToFile("config/CarConfigList",b);break;case "loading":this.send2web(b);this.send2ue4(this.WeatherInfo);this.send2ue4(this.TrafficInfo);this.send2ue4(this.CarConfig);this.send2ue4(this.CaseList);break;case "car_state":this.CarState=b;a.isWeb()?this.send2ue4(this.CarState):a.isUE4()&&this.send2web(this.CarState);break;case "case_list":this.CaseList=b;FileHelper.saveJSONToFile("config/CaseList",b);a.isWeb()?this.send2ue4(b):a.isUE4()&&this.send2web(b);
break;case "case_info":a.isWeb()?this.send2ue4(b):a.isUE4()&&this.send2web(b);break;case "sumo_info":a.isWeb()?this.send2ue4(b):a.isUE4()&&this.send2web(b);break;case "drive_info":a.isRos()?this.send2web(b):a.isWeb()&&this.send2ros(b);break;case "topic_info":a.isTopic()&&this.send2web(b);break;case "get":b.value=FileHelper.loadStringFromFile(b.key);a.send(b);break;case "set":FileHelper.saveStringToFile("db/"+b.key,b.value);break;case "ping":break;default:console.log("|||||||||||||||unknow pack:%s",
b.method)}}}exports.LogicServer=LogicServer;
